spring:
  datasource: #database source 작성
    url: ENC(Nsv9fohdNbgqHIwwzTZvNzDr00FSSuOkjxKpeV1Qp3XoYwAn3dZKejdrL9YHsQsRPjDcZ4Imdm+G0P72mVktwqIeUqagIxaW4UFdV36GvGaQoIpoxuUSrRGr2zrfHazS)
    username: ENC(Qx+ss9Rro1FZ0nIrvGUkwA==)
    password: ENC(QwN8qu+dI5n8qkyB+msamg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update # application 실행 시점에 기존 ddl 정보를 다 지우고 다시 실행시킨다.
    properties:
      hibernate:
        show_sql: true # jpa, hibernate가 생성하는 모든 sql이 sout으로 찍힌다
#         운영환경에서는 sout이 아닌 log로 나타내야 한다
        format_sql: true
    generate-ddl: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor